name: Build and Publish cleanreg

on:
  push:
    branches:
      - 'main'
      - 'pr/**'
      - 'feature/**'
    paths-ignore:
      - 'README.md'

  release:
    types: [published]

  workflow_dispatch:

jobs:

  test-cleanreg:
    runs-on: 'ubuntu-20.04'

    steps:

      - uses: actions/checkout@v2

      - run: |
          cd test
          chmod +x runAllTests.sh
          ./runAllTests.sh
        name: Execute tests
        shell: bash --noprofile --norc {0}

  package:
    runs-on: 'ubuntu-20.04'
    needs: test-cleanreg
    # create the images and push them only if on a release tag, starting with a 'v'
    if: startsWith(github.ref, 'refs/tags/v')
    steps:

      # here we create the version information based on the tag and the commit sha
      # but only if we are building from a tag reference
      - name: Create tags
        id: create_tags
        run: |
          DOCKER_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/cleanreg
          SHORTREF=${GITHUB_SHA::8}
          VERSION=${{ github.ref_name }}
          RUN_NUMBER=${{ github.run_number }}

          TAGS="${DOCKER_IMAGE}:${VERSION},${DOCKER_IMAGE}:${VERSION}-${SHORTREF}-${RUN_NUMBER}"

          echo "::set-output name=tags::${TAGS}"
        shell: bash

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.create_tags.outputs.tags }}